// <auto-generated />
using MVC.databaseClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(applicationDbContext))]
    partial class applicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("MVC.databaseClasses.miniature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pressure")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Temp")
                        .HasColumnType("REAL");

                    b.Property<float>("Temp_Max")
                        .HasColumnType("REAL");

                    b.Property<float>("Temp_Min")
                        .HasColumnType("REAL");

                    b.Property<bool>("databaseReady")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Miniatures");
                });
#pragma warning restore 612, 618
        }
    }
}
